- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/PasscodeView.java
- TMessagesProj/src/main/java/org/telegram/ui/PasscodeActivity.java
- TMessagesProj/src/main/res/values/strings.xml
Close #10. 
Need a review to understand if I did it right.
> Add second SMS

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/TelegramMessageAction.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/FilterUsersActivity.java
- TMessagesProj/src/main/res/values/strings.xml
Close #25.
Остались только пара технических вопросов. Можно ли как-то фильтровать выбор чатов? Было бы очень круто
> Send telegram messages

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/TelegramMessageAction.java
Ненадолго оживим эту ветку. Нашел, как правильно искать `id` отправленного экстренного сообщения и добавил его удаление.
> Add removing emergency message

- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- TMessagesProj/src/main/java/org/telegram/ui/PasscodeActivity.java
fix #51
Вроде, должно работать. Если я правильно понял суть
> fix fake passcode deletion

- .github/workflows/main.yml
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeTelegramMessagesActivity.java
Думаю, можно новую версию выпустить. Заодно забрав сегодняшнее обновление из официального репозитория
> Fix chat activities

- TMessagesProj/src/main/java/org/telegram/ui/ContactAddActivity.java
> do not share phone number with contacts

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/ClearProxiesAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeActivity.java
- TMessagesProj/src/main/res/values/strings.xml
> add clear proxies action

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/AccountAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/AccountActions.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/DeleteContactsAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/DeleteStickersAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/LogOutAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveChatsAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/TelegramMessageAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/TerminateOtherSessionsAction.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeAccountActionsActivity.java
- TMessagesProj/src/main/res/values/strings.xml
> Remove stickers

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/ui/LoginActivity.java
- TMessagesProj/src/main/res/values/strings.xml
close #64
Ну и заодно добавил проверку настроек приватности. Если у пользователя телефон, время последней активности и звонки не доступны для всех, то считаю, что он разобрался с настройками приватности и приставать к нему не нужно. Если нет, предлагаю всё на максимум выставить.
> Add two factor notice

- TMessagesProj/src/main/java/org/telegram/messenger/GcmPushListenerService.java
- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/MessagesController.java
- TMessagesProj/src/main/java/org/telegram/messenger/MessagesStorage.java
- TMessagesProj/src/main/java/org/telegram/messenger/NotificationsController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeActivity.java
- TMessagesProj/src/main/res/values/strings.xml
close #65 
Пока работает кривовато, ведь сообщение может прийти чёрт знает когда. Может как push прийти, может, когда приложение открыто. Но, думаю, лучше пусть так, чем никак.
> add activation message

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogsActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/LoginActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/TwoStepVerificationSetupActivity.java
- TMessagesProj/src/main/res/values/strings.xml
Исправил переход на установку пароля
> fix 2-step verification dialog

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
close #72 
close #71 
Я так понимаю, проблема была в этом. Накосячил я. Теперь надо пересобрать, прошлую версию объявить бракованной
> fix activation message

- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeTelegramMessagesActivity.java
В messages activity использовался не тот аккаунт
> fix tg messages activity

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/ClearProxiesAction.java
> fix proxy deletion

- TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java
- TMessagesProj/src/main/java/org/telegram/ui/ProfileActivity.java
> add partisan telegram version

- TMessagesProj/build.gradle
- TMessagesProj/src/main/java/org/telegram/messenger/BadPasscodeAttempt.java
- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/MessagesController.java
- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/ui/Adapters/DrawerLayoutAdapter.java
- TMessagesProj/src/main/java/org/telegram/ui/BadPasscodeAttemptsActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/Cells/BadPasscodeCell.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/PasscodeView.java
- TMessagesProj/src/main/java/org/telegram/ui/ContactAddActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/LoginActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/PasscodeActivity.java
- TMessagesProj/src/main/res/values/strings.xml
> Bad passcode tries

- TMessagesProj/src/main/java/org/telegram/ui/DialogsActivity.java
> lock the app immediately

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/AccountActions.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/ClearProxiesAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/ClearSearchHistoryAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeAccountActionsActivity.java
> clear search history

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/TelegramMessageAction.java
Повторить оповещение не вышло, возможно это из-за того, что я отсылал сообщения между своими аккаунтами, которые висят на клиенте. Зато пока это делал, увидел баг: при втором и так далее введении ложного пароля сообщение остается в `ChatActivity` (не видны в общем списке, но если открыть чат, то будет видно). Сейчас должно быть пофикшено.
> Fix message in chat

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveChatsAction.java
> fix chat deletion from folder

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogsActivity.java
- TMessagesProj/src/main/res/values/strings.xml
> app updates notification

- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- TMessagesProj/src/main/java/org/telegram/ui/CacheControlActivity.java
> clear cache after 1 day

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/MessagesController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/TelegramMessageAction.java
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogBuilder/FakePasscodeDialogBuilder.java
- TMessagesProj/src/main/java/org/telegram/ui/ProfileActivity.java
- TMessagesProj/src/main/res/values/strings.xml
Пофиксил баг с удалением в чатах, где `isChannel` отдает `true`. Добавил регулярки, но чек-бокс смотрится как-то странно, но я не понял, почему. Добавил промежуточный диалог для подтверждения удаления.
> Fix bugs and improve deleting messages

- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
Пофиксил зависимость регистра в регулярке.
> Fix regex case

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveAsReadMessages.java
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/AlertsCreator.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/ChatActivityEnterView.java
- TMessagesProj/src/main/res/values/strings.xml
Добавил возможность отправки сообщений, которые удалятся после прочтения после заданного при отправке промежутка времени
> Remove as read messages

- TMessagesProj/src/main/java/org/telegram/messenger/SendMessagesHelper.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveAsReadMessages.java
- TMessagesProj/src/main/java/org/telegram/ui/Cells/DialogCell.java
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/AlertsCreator.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/ChatActivityEnterView.java
- TMessagesProj/src/main/java/org/telegram/ui/Components/ChatAttachAlert.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogsActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/PhotoViewer.java
Пофиксил появление автоудаления вместо отправки без сжатия в PhotoViewer, добавил сохранение времени удаления отдельно по аккаунтам
> Fix autodelete in photoviewer, add saving delays

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/AccountActions.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/ClearBlackListAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/ClearSearchHistoryAction.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveChatsAction.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeAccountActionsActivity.java
- TMessagesProj/src/main/res/values/strings.xml
- gradle/wrapper/gradle-wrapper.properties
Close #141 
1. Пофиксил очистку чата с ботом. Теперь он не блокируется.
2. Пофиксил сообщение об очистке сеансов.
3. Добавил опцию очистки ЧС.
> Fix bot deletion

- TMessagesProj/src/main/java/org/telegram/ui/Cells/ChatMessageCell.java
> Fix chat renaming

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/ui/ProfileActivity.java
- TMessagesProj/src/main/res/values-es/strings.xml
- TMessagesProj/src/main/res/values/strings.xml
> Show chat id

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/res/values/strings.xml
В описание кнопки удаления сообщений добавил акцент, что удаляются именно сообщения владельца, переименовал расширенное удаление в английской версии.
> Fix delete message description

- TMessagesProj/src/main/java/org/telegram/messenger/Utilities.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveAsReadMessages.java
- TMessagesProj/src/main/java/org/telegram/ui/Cells/DialogCell.java
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java
Добавил время прочтения, что позволяет при перезагрузке приложения перезапустить таймер удаления и удалить сообщения, срок которых уже вышел.
> Add read time

- TMessagesProj/src/main/java/org/telegram/messenger/Utilities.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/Utils.java
- TMessagesProj/src/main/java/org/telegram/ui/Cells/DialogCell.java
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java
Пофиксил вылеты приложения от `ConcurrentModificationException`
> Fix ConcurrentModification on startup

- TMessagesProj/src/main/java/org/telegram/messenger/camera/HiddenCameraManager.java
> hidden camera: unmute audio

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/FakePasscode.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveChatsAction.java
- TMessagesProj/src/main/java/org/telegram/ui/FakePasscodeActivity.java
- TMessagesProj/src/main/res/values/strings.xml
> clear passcode and delete other passcodes

- TMessagesProj/src/main/java/org/telegram/messenger/MessagesStorage.java
- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/RemoveChatsAction.java
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
> fix chat hiding

- TMessagesProj/src/main/java/org/telegram/messenger/fakepasscode/DeleteStickersAction.java
> task-252 delete recent emoji

- TMessagesProj/src/main/assets/strings/strings_be.xml
- TMessagesProj/src/main/assets/strings/strings_pl.xml
- TMessagesProj/src/main/assets/strings/strings_ru.xml
- TMessagesProj/src/main/assets/strings/strings_uk.xml
- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogBuilder/CheckBoxTemplate.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogBuilder/DialogTemplate.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogBuilder/EditTemplate.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogBuilder/FakePasscodeDialogBuilder.java
- TMessagesProj/src/main/res/values/strings.xml
@vivabelarus  please take care of the translations.
> some fixes

- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
> add warning to group invite
